CREATE TABLE bankaccount (
   AccountNumber INT PRIMARY KEY,
   Balance DECIMAL(15,2) NOT NULL,
   AccountType VARCHAR(20) NOT NULL,
   GovtId VARCHAR(20) NOT NULL,
   CONSTRAINT CGovtid_FK  FOREIGN KEY (GovtId) REFERENCES KYC(GovtId)
 );