CREATE TABLE BANKATMCARD(
   CardNumber VARCHAR(16) PRIMARY KEY,
   CVV VARCHAR(3) NOT NULL,
   CardHolderName VARCHAR(100) NOT NULL,
   ExpiryMonth int NOT NULL,
   ExpiryYear int NOT NULL,
   UPIId int NOT NULL,
   AccountNumber int NOT NULL,
   CONSTRAINT C_AccNum_FK FOREIGN KEY (AccountNumber) REFERENCES bankaccount(AccountNumber),
   CONSTRAINT C_UPIId_FK FOREIGN KEY (UPIId) REFERENCES  UPI(UPIID)
 );