CREATE TABLE KYC (
   GovtId VARCHAR(20) PRIMARY KEY,
   FirstName VARCHAR(60) NOT NULL,
   LastName VARCHAR(60) NOT NULL,
   DOB Date  NOT NULL,
   Nationality VARCHAR(50),
   Gender VARCHAR(10) NOT NULL
 );
