CREATE TABLE TRANSACTIONS (
   TRANSACTIONSID INT PRIMARY KEY,
   TRANSACTIONSDATE DATE NOT NULL,
   TRANSACTIONSTIME TIMESTAMP NOT NULL,
   TRANSACTIONSLIMIT DECIMAL(15,2),
   TRANSACTIONSAMOUNT DECIMAL(15,2) NOT NULL,
   TRANSACTIONSTYPE VARCHAR(10) NOT NULL,
   CREDIT TINYINT(1),
   DEBIT TINYINT(1),
   CARDNUMBER VARCHAR(16),
   CONSTRAINT C_CardNum_FK FOREIGN KEY (CARDNUMBER) REFERENCES BANKATMCARD (CARDNUMBER)
 );
