INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (1, 123456, 'Transaction1', 'Customer Support1', 'Refunds1', 1);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (2, 789012, 'Transaction2', 'Customer Support2', 'Refunds2', 2);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (3, 345678, 'Transaction3', 'Customer Support3', 'Refunds3', 3);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (4, 901234, 'Transaction4', 'Customer Support4', 'Refunds4', 4);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (5, 567890, 'Transactions', 'Customer Support5', 'Refunds5', 5);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (6, 234567, 'Transaction6', 'Customer Support6', 'Refunds6', 6);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (7, 678901, 'Transaction7', 'Customer Support7', 'Refunds7', 7);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (8, 345678, 'Transaction8', 'Customer Support8', 'Refunds8', 8);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (9, 999999, 'Transaction9', 'Customer Support9', 'Refunds9', 9);

INSERT INTO `UPI` (`UPIID`, `UPINUMBER`, `TRANSACTIONHISTORY`, `CUSTOMERSUPPORT`, `REFUNDS`, `USERID`) 
VALUES (10, 456789, 'Transaction10', 'Customer Support10', 'Refunds10', 10);